<a href="https://colab.research.google.com/github/Verokai/dap-2024/blob/main/les03/lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторная работа №3. NumPy

## Отчет по заданию

Выполнили следующие задания:

1. Открыли файл в Google Colab.
2. Решили задачи.
3. Сохранили результат в свой репозиторий github в директорию ./les03
4. Создали pull request в репозиторий https://github.com/chebotarevsa/dap-2024. Название pull request должно иметь формат "<Номер лабораторной работы>  <Номер группы> <ФИО>"
5. Сдали работу в системе "Пегас", в отчете указали ссылку на pull request

In [ ]:
import numpy as np
np.version.version

'2.0.2'

1. Создать массив 10x10 со случайными значениями, найти минимум и максимум (низкая)

In [3]:
import numpy as np
# Создаем массив 10x10 со случайными значениями от -1000 до 1000
array = np.random.randint(-1000, 1001, size=(10, 10))

min_value = np.min(array)
max_value = np.max(array)

print("Массив 10x10:")
print(array)
print("\nМинимальное значение:" + str(min_value))
print("Максимальное значение:" + str(max_value))

Массив 10x10:
[[ 708 -211 -418 -501  218  582  584  833 -745  814]
 [ 837  788  414  782 -566  792 -128  384  457  468]
 [ 383 -610  119  547  710  659   76 -153 -459 -124]
 [-852 -257  838  341 -181 -405  825  -45 -601  577]
 [-232 -657 -267  938  690 -930 -997 -400 -326 -531]
 [ 973  -18  -20 -412 -328  185  -43  685 -937  913]
 [ 634  409 -744 -570  122  951 -122  625  568  890]
 [-237  -13  127  659  795  408  858 -972  537   97]
 [-146  751 -849  299 -351  157  858 -258 -815 -549]
 [ 811   26  959  -61  231  537 -346 -912 -653 -302]]

Минимальное значение:-997
Максимальное значение:973


2. Создать 8x8 матрицу и заполнить её единицами и нулями в шахматном порядке

In [6]:
import numpy as np
# Создаем матрицу 8x8 и заполняем нулями
chessboard = np.zeros((8, 8), dtype=int)
for i in range(8):
    for j in range(8):
        # Клетка черная, если сумма индексов четная
        if (i + j) % 2 != 0:
            chessboard[i,j]=1
# Выводим матрицу
print("Шахматная доска 8x8:")
for row in chessboard:
    print(row)

Шахматная доска 8x8:
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]


3. Дан массив из 11 элементов, поменять знак у элементов, значения которых между 3 и 8

In [8]:
z = np.arange(11)
for i in range(len(z)):
  if 3< z[i]< 8:
    z[i]*=-1
print(z)

#Второй вариант решения
import numpy as np
z = np.arange(11)
# Меняем знак у элементов, значения которых между 3 и 8 (исключая границы)
z[(z > 3) & (z < 8)] *= -1
print(z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


4. Найти среднее заначение строки матрицы и вычесть его из каждого елемента строки

In [10]:
import numpy as np
z = np.random.rand(5, 10)
z_centered = z - z.mean(axis=1, keepdims=True)

print("Исходная матрица:")
print(z)
print("\nИтоговая матрица:")
print(z_centered)

Исходная матрица:
[[0.44727029 0.0407528  0.397178   0.6708428  0.78507502 0.02404005
  0.82298708 0.91491756 0.06738716 0.67204509]
 [0.67056607 0.9724342  0.27286726 0.90160416 0.7570411  0.58323393
  0.30676553 0.75288934 0.0833521  0.82395836]
 [0.76766961 0.5259107  0.94156852 0.26045274 0.70488394 0.62001376
  0.34653088 0.51503091 0.86915832 0.31964042]
 [0.88042884 0.73527615 0.6749849  0.53490499 0.94556836 0.39388158
  0.75770999 0.42661392 0.05457774 0.62641496]
 [0.82809289 0.87625043 0.21861549 0.73726443 0.28432515 0.48804966
  0.21397835 0.28878652 0.70882365 0.08335819]]

Итоговая матрица:
[[-0.0369793  -0.44349678 -0.08707158  0.18659322  0.30082543 -0.46020954
   0.33873749  0.43066798 -0.41686242  0.1877955 ]
 [ 0.05809487  0.35996299 -0.33960394  0.28913295  0.1445699  -0.02923728
  -0.30570568  0.14041814 -0.5291191   0.21148716]
 [ 0.18058363 -0.06117528  0.35448254 -0.32663324  0.11779796  0.03292778
  -0.2405551  -0.07205507  0.28207234 -0.26744556]
 [ 0.2773927

5. Поменяйте 1 и 2 строки матрицы

In [12]:
import numpy as np
z = np.arange(25).reshape(5,5)
# Создаем копию матрицы с переставленными строками
z_swapped = z.copy()
z_swapped[0] = z[1]
z_swapped[1] = z[0]
print("Исходная матрица:")
print(z)
print("Матрица с переставленными строками:")
print(z_swapped)

Исходная матрица:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Матрица с переставленными строками:
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


6. Дан массив 10x2 подеставлющий собой точки в декартовой системе координат, преобразовать в полярную

In [13]:
import numpy as np

z = np.random.random((10, 2))

# Преобразуем декартовы координаты в полярные
x = z[:, 0]  # координаты x
y = z[:, 1]  # координаты y

# Вычисляем радиус (r) и угол (phi)
r = np.sqrt(x**2 + y**2)  # расстояние от начала координат
phi = np.arctan2(y, x)    # угол в радианах

# Собираем результат в массив той же формы (10, 2)
polar_coords = np.column_stack((r, phi))

print("Декартовы координаты:")
print(z)
print("\nПолярные координаты (радиус, угол в радианах):")
print(polar_coords)

Декартовы координаты:
[[0.32086536 0.53623208]
 [0.97260979 0.04153484]
 [0.18907892 0.00549187]
 [0.66178561 0.27130482]
 [0.04769632 0.94178565]
 [0.31285878 0.17987624]
 [0.67411664 0.13687225]
 [0.44958624 0.73315231]
 [0.90685661 0.09251847]
 [0.73996807 0.48363729]]

Полярные координаты (радиус, угол в радианах):
[[0.62489953 1.03157599]
 [0.97349624 0.04267859]
 [0.18915866 0.0290372 ]
 [0.71523877 0.38906195]
 [0.94299266 1.520195  ]
 [0.36088236 0.5217921 ]
 [0.68787154 0.20031637]
 [0.86002331 1.02071035]
 [0.91156381 0.10166929]
 [0.884001   0.57889628]]


7. Заменить максимальный элемент массива на ноль

In [14]:
import numpy as np

z = np.random.random(10)
print("Исходный массив:")
print(z)
# Находим индекс максимального элемента
max_index = np.argmax(z)

# Заменяем максимальный элемент на 0
z[max_index] = 0

print("Массив после замены максимального элемента на 0:")
print(z)

Исходный массив:
[0.38279857 0.46547787 0.82003531 0.62866722 0.88052485 0.61943791
 0.39524795 0.87304315 0.34329566 0.98943076]
Массив после замены максимального элемента на 0:
[0.38279857 0.46547787 0.82003531 0.62866722 0.88052485 0.61943791
 0.39524795 0.87304315 0.34329566 0.        ]


8. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве. Добавление производиться только 1 раз

In [20]:
import numpy as np

z = np.ones(10)
print("Первый массив:", z)
i = np.random.randint(0, len(z), 20)#Заполнить значениями от 0 до 10, размер массива 20

#Избавляемся от повторений
unique_indices = np.unique(i)

# Добавляем 1 к элементам с уникальными индексами
z[unique_indices] += 1

print("Массив индексов i:", i)
print("Массив без повторений:", unique_indices)
print("Результат:")
print(z)

Первый массив: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Массив индексов i: [5 3 4 1 0 5 4 1 7 5 0 1 4 8 2 0 1 0 8 5]
Массив без повторений: [0 1 2 3 4 5 7 8]
Результат:
[2. 2. 2. 2. 2. 2. 1. 2. 2. 1.]


9. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [ ]:
import numpy as np
z = np.array([1, 2, 3, 4, 5])

# Создаем новый массив с нулями между элементами
# Длина нового массива: исходная длина + (количество промежутков * 3)
new_length = len(z) + (len(z) - 1) * 3
result = np.zeros(new_length, dtype=z.dtype)

# Заполняем позиции исходными значениями
# Исходные элементы размещаются на позициях: 0, 4, 8, 12, 16
result[::4] = z

print(result)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


10. Найти ближайшее к заданному значению число в заданном массиве

In [24]:
import numpy as np

z = np.arange(100)  # Массив чисел от 0 до 99
v = np.random.uniform(0, 100)  # Случайное число от 0 до 100

# Находим индекс элемента, наиболее близкого к v
idx = (np.abs(z - v)).argmin()
nearest_value = z[idx]

print(f"Случайное число v: {v}")
print(f"Ближайшее число в массиве z: {nearest_value}")

Случайное число v: 84.8771961418341
Ближайшее число в массиве z: 85


## Вопросы




**1**. Какой тип (dtype) будут иметь элементы массива?
``` python
np.array([1, 4, 2, 5, 3])
np.array([1., 4, 2, 5, 3])
np.array([1, 4, 2, 5, 3], dtype='float128')
np.array([1., 4, 2, 5, 3], dtype='complex128')
np.array([1, 4, 2, 5, 3], dtype ='float64')
np.array([1, 4, 2, 5, 3], dtype =int64)
np.array([1, 4, 2, 5, 3], dtype='bool')
np.array([1, 4, 2, 5, 3], dtype='str')
np.array([1, 4, 2, 5, '3'])
np.array([1, -4, 2, 0, 1j])
```

**2**. Что будет выведено в консоль и почему?
``` python
np.array([1, 4, 2, 5, 3], dtype='str')[1] + '1'
np.array([1, -4, 2, 0, 3], dtype='bool')[3] or np.array([1, -4, 2, 0, 3])[1]
np.array([1, -4, 2, 0, 3], dtype='bool')[3] and np.array([1, -4, 2, 0, 3])[1]
np.array([1, -4, 2, 0, True], dtype='int64')[-1]
np.array([1, -4, 2, 0, 1j], dtype='int64')[1]
np.array([1, -4, 2, 0, 1j], dtype='str')[-1]
np.array([1, 4, 2, 5, '3'])[-1] * 3
```

**3**. Каков результат операции?

``` python
np.ones((3, 5), dtype=float)
np.full((3, 5), 3.14)
np.linspace(0, 1, 5)
np.diag((1,3,5))
np.smile((1,3,5))
np.random.random((3, 3))
np.eye(3)
np.empty(3)
```



**4**. Дан двумерный массив X, что будет выведено в консоль?

``` python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])
```

``` python
X[0,0]
X[-1,-1]
X[0:1,-1]
X[0:2,-1]
X[0:2,0:2]
X[1,1:3]
X[1,:]
X[1,:]
X[:,:]
X[:]
X[::2,::2]
X[0:3:2,0:3:2]
X[::-1,::-1]
```

**5**. Дан двумерный массив grid, в чем различее между операциями?


``` python
grid = np.arange(16).reshape((4, 4))
```

``` python
np.split(grid, [2])
np.split(grid, [2], axis=1)
```


**6**. В чем различие между операциями?

``` python
    [1, 2, 3] + [3, 2, 1]
    np.array([1, 2, 3]) + np.array([3, 2, 1])
```

**7**. Как в CodeLab измерить время выполнения кода?

**8**. Дан массив X, каковы результаты операций?

```python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])

np.sum(M)
np.sum(M, axis=1)
np.sum(M, axis=0)
np.sum(M, axis=2)
np.sum(M, 1)
sum(M)
sum(M,1)
```

**9**. Дан массив X, что будет выведено в консоль?

```python
X = np.array([1,2,3,4])

X > 3
X < 3
X[X < 3]
X[X > 3]
X[X != 3]
```

**10**.  В чем преимущество массивов NumPy по сравнению с обычными списками.  Чем обусловлено это преимущество?