<a href="https://colab.research.google.com/github/Verokai/dap-2024/blob/main/les03/lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторная работа №3. NumPy

## Отчет по заданию

Выполнили следующие задания:

1. Открыли файл в Google Colab.
2. Решили задачи.
3. Сохранили результат в свой репозиторий github в директорию ./les03
4. Создали pull request в репозиторий https://github.com/chebotarevsa/dap-2024. Название pull request должно иметь формат "<Номер лабораторной работы>  <Номер группы> <ФИО>"
5. Сдали работу в системе "Пегас", в отчете указали ссылку на pull request

In [1]:
import numpy as np
np.version.version

'2.0.2'

1. Создать массив 10x10 со случайными значениями, найти минимум и максимум (низкая)

In [5]:
import numpy as np
# Создаем массив 10x10 со случайными значениями от -1000 до 1000
array = np.random.randint(-1000, 1001, size=(10, 10))

min_value = np.min(array)
max_value = np.max(array)

print("Массив 10x10:")
print(array)
print("\nМинимальное значение: {min_value}")
print("Максимальное значение: {max_value}")

Массив 10x10:
[[-305 -137 -533  291 -692  648 -408 -959 -516 -583]
 [-411 -867  100  708  245  824 -607 -982 -210  964]
 [  78 -887 -684  213 -353  611 -603  -67 -480 -723]
 [-578  427 -222  994  245 -417  639 -829 -986  691]
 [-789  895  112 -112   92  688  101 -847  284 -878]
 [ 359 -155  159  312  561 -543  596  141  246 -633]
 [ 303 -409 -958 -930  795  270  408 -619  314  633]
 [ 168  380  378  598  505 -908  191  678 -541 -545]
 [ 164 -216 -458  178 -294    6 -392  -80 -193 -454]
 [ 982  426  140 -490  546 -579  543 -296  503  932]]

Минимальное значение: {min_value}
Максимальное значение: {max_value}


2. Создать 8x8 матрицу и заполнить её единицами и нулями в шахматном порядке

In [9]:
import numpy as np
# Создаем матрицу 8x8, заполняем 0
chessboard = np.zeros((8, 8), dtype=int)

# Заполняем черные клетки единицами (шахматный порядок)
chessboard[1::2, ::2] = 1  # Нечетные строки, четные столбцы
chessboard[::2, 1::2] = 1  # Четные строки, нечетные столбцы

# Выводим матрицу
print("Шахматная доска 8x8:")
print(chessboard)

print("Второй вариант решения задачи")
# Создаем матрицу 8x8 в шахматном порядке без NumPy
chessboard = []
for i in range(8):
    row = []
    for j in range(8):
        # Клетка черная, если сумма индексов четная
        if (i + j) % 2 == 0:
            row.append(0)
        else:
            row.append(1)
    chessboard.append(row)

# Выводим матрицу
print("Шахматная доска 8x8:")
for row in chessboard:
    print(row)

Шахматная доска 8x8:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
Второй вариант решения задачи
Шахматная доска 8x8:
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]


3. Дан массив из 11 элементов, поменять знак у элементов, значения которых между 3 и 8

In [16]:
z = np.arange(11)
for i in range(len(z)):
  if 3< z[i]< 8:
    z[i]*=-1
print(z)

#Второй вариант решения
import numpy as np
z = np.arange(11)
# Меняем знак у элементов, значения которых между 3 и 8 (исключая границы)
z[(z > 3) & (z < 8)] *= -1
print(z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


4. Найти среднее заначение строки матрицы и вычесть его из каждого елемента строки

In [32]:
import numpy as np
z = np.random.rand(5, 10)
z_centered = z - z.mean(axis=1, keepdims=True)

print("Исходная матрица:")
print(z)
print("\nМатрица после центрирования:")
print(z_centered)

Исходная матрица:
[[0.3042948  0.99673763 0.47832717 0.20321136 0.69498092 0.62923479
  0.10479959 0.81881004 0.38340714 0.26749636]
 [0.16101941 0.96367234 0.41345    0.31385207 0.05583126 0.47873902
  0.57874695 0.1972034  0.59895247 0.77112918]
 [0.58299992 0.55711737 0.18710764 0.834882   0.25264732 0.51502931
  0.06890056 0.06839851 0.07092315 0.81251144]
 [0.30092081 0.91038177 0.25496655 0.36958748 0.89963855 0.68945757
  0.4851865  0.81221226 0.82053651 0.35778928]
 [0.34503696 0.05315008 0.94035919 0.02988963 0.3618048  0.81162094
  0.65666056 0.676662   0.3576394  0.28563068]]

Матрица после центрирования:
[[-0.18383518  0.50860765 -0.00980281 -0.28491862  0.20685094  0.14110481
  -0.38333039  0.33068006 -0.10472284 -0.22063362]
 [-0.2922402   0.51041273 -0.03980961 -0.13940754 -0.39742835  0.02547941
   0.12548734 -0.25605621  0.14569286  0.31786957]
 [ 0.1879482   0.16206564 -0.20794408  0.43983028 -0.1424044   0.11997759
  -0.32615116 -0.32665322 -0.32412857  0.41745972]
 

5. Поменяйте 1 и 2 строки матрицы

In [35]:
import numpy as np
z = np.arange(25).reshape(5,5)
# Создаем копию матрицы с переставленными строками
z_swapped = z.copy()
z_swapped[0] = z[1]
z_swapped[1] = z[0]
print("Исходная матрица:")
print(z)
print("Матрица с переставленными строками:")
print(z_swapped)

Исходная матрица:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Матрица с переставленными строками:
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


6. Дан массив 10x2 подеставлющий собой точки в декартовой системе координат, преобразовать в полярную

In [36]:
import numpy as np

z = np.random.random((10, 2))

# Преобразуем декартовы координаты в полярные
x = z[:, 0]  # координаты x
y = z[:, 1]  # координаты y

# Вычисляем радиус (r) и угол (phi)
r = np.sqrt(x**2 + y**2)  # расстояние от начала координат
phi = np.arctan2(y, x)    # угол в радианах

# Собираем результат в массив той же формы (10, 2)
polar_coords = np.column_stack((r, phi))

print("Декартовы координаты:")
print(z)
print("\nПолярные координаты (радиус, угол в радианах):")
print(polar_coords)

Декартовы координаты:
[[0.47406259 0.47819209]
 [0.89555007 0.12472481]
 [0.86092854 0.34036299]
 [0.89376495 0.10304334]
 [0.54704882 0.83917854]
 [0.8185587  0.22886814]
 [0.98830626 0.52605984]
 [0.47357305 0.31621503]
 [0.91774458 0.04922505]
 [0.76850969 0.24929564]]

Полярные координаты (радиус, угол в радианах):
[[0.67335208 0.78973468]
 [0.90419368 0.1383816 ]
 [0.92576721 0.37648621]
 [0.89968534 0.11478453]
 [1.00174    0.99309634]
 [0.84995233 0.27263676]
 [1.11959288 0.4891402 ]
 [0.56944129 0.5887327 ]
 [0.91906378 0.05358563]
 [0.80793283 0.31367865]]


7. Заменить максимальный элемент массива на ноль

In [38]:
import numpy as np

z = np.random.random(10)
print("Исходный массив:")
print(z)
# Находим индекс максимального элемента
max_index = np.argmax(z)

# Заменяем максимальный элемент на 0
z[max_index] = 0

print("Массив после замены максимального элемента на 0:")
print(z)

Исходный массив:
[0.37591456 0.35091871 0.14133802 0.60651258 0.81408591 0.74883811
 0.47565794 0.42085914 0.73681208 0.57536981]
Массив после замены максимального элемента на 0:
[0.37591456 0.35091871 0.14133802 0.60651258 0.         0.74883811
 0.47565794 0.42085914 0.73681208 0.57536981]


8. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве. Добавление производиться только 1 раз

In [39]:
import numpy as np

z = np.ones(10)
i = np.random.randint(0, len(z), 20)

# Находим уникальные индексы, чтобы добавить 1 только один раз для каждого индекса
unique_indices = np.unique(i)

# Добавляем 1 к элементам с уникальными индексами
z[unique_indices] += 1

print("Массив индексов i:", i)
print("Уникальные индексы:", unique_indices)
print("Результат:")
print(z)

Массив индексов i: [6 6 5 5 6 8 8 6 6 2 7 0 3 4 0 2 5 7 5 0]
Уникальные индексы: [0 2 3 4 5 6 7 8]
Результат:
[2. 1. 2. 2. 2. 2. 2. 2. 2. 1.]


9. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [40]:
import numpy as np
z = np.array([1, 2, 3, 4, 5])

# Создаем новый массив с нулями между элементами
# Длина нового массива: исходная длина + (количество промежутков * 3)
new_length = len(z) + (len(z) - 1) * 3
result = np.zeros(new_length, dtype=z.dtype)

# Заполняем позиции исходными значениями
# Исходные элементы размещаются на позициях: 0, 4, 8, 12, 16
result[::4] = z

print(result)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


10. Найти ближайшее к заданному значению число в заданном массиве

In [42]:
import numpy as np

z = np.arange(100)  # Массив чисел от 0 до 99
v = np.random.uniform(0, 100)  # Случайное число от 0 до 100

# Находим индекс элемента, наиболее близкого к v
idx = (np.abs(z - v)).argmin()
nearest_value = z[idx]

print(f"Случайное число v: {v}")
print(f"Ближайшее число в массиве z: {nearest_value}")

Случайное число v: 38.4436289557071
Ближайшее число в массиве z: 38


## Вопросы




**1**. Какой тип (dtype) будут иметь элементы массива?
``` python
np.array([1, 4, 2, 5, 3])
np.array([1., 4, 2, 5, 3])
np.array([1, 4, 2, 5, 3], dtype='float128')
np.array([1., 4, 2, 5, 3], dtype='complex128')
np.array([1, 4, 2, 5, 3], dtype ='float64')
np.array([1, 4, 2, 5, 3], dtype =int64)
np.array([1, 4, 2, 5, 3], dtype='bool')
np.array([1, 4, 2, 5, 3], dtype='str')
np.array([1, 4, 2, 5, '3'])
np.array([1, -4, 2, 0, 1j])
```

**2**. Что будет выведено в консоль и почему?
``` python
np.array([1, 4, 2, 5, 3], dtype='str')[1] + '1'
np.array([1, -4, 2, 0, 3], dtype='bool')[3] or np.array([1, -4, 2, 0, 3])[1]
np.array([1, -4, 2, 0, 3], dtype='bool')[3] and np.array([1, -4, 2, 0, 3])[1]
np.array([1, -4, 2, 0, True], dtype='int64')[-1]
np.array([1, -4, 2, 0, 1j], dtype='int64')[1]
np.array([1, -4, 2, 0, 1j], dtype='str')[-1]
np.array([1, 4, 2, 5, '3'])[-1] * 3
```

**3**. Каков результат операции?

``` python
np.ones((3, 5), dtype=float)
np.full((3, 5), 3.14)
np.linspace(0, 1, 5)
np.diag((1,3,5))
np.smile((1,3,5))
np.random.random((3, 3))
np.eye(3)
np.empty(3)
```



**4**. Дан двумерный массив X, что будет выведено в консоль?

``` python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])
```

``` python
X[0,0]
X[-1,-1]
X[0:1,-1]
X[0:2,-1]
X[0:2,0:2]
X[1,1:3]
X[1,:]
X[1,:]
X[:,:]
X[:]
X[::2,::2]
X[0:3:2,0:3:2]
X[::-1,::-1]
```

**5**. Дан двумерный массив grid, в чем различее между операциями?


``` python
grid = np.arange(16).reshape((4, 4))
```

``` python
np.split(grid, [2])
np.split(grid, [2], axis=1)
```


**6**. В чем различие между операциями?

``` python
    [1, 2, 3] + [3, 2, 1]
    np.array([1, 2, 3]) + np.array([3, 2, 1])
```

**7**. Как в CodeLab измерить время выполнения кода?

**8**. Дан массив X, каковы результаты операций?

```python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])

np.sum(M)
np.sum(M, axis=1)
np.sum(M, axis=0)
np.sum(M, axis=2)
np.sum(M, 1)
sum(M)
sum(M,1)
```

**9**. Дан массив X, что будет выведено в консоль?

```python
X = np.array([1,2,3,4])

X > 3
X < 3
X[X < 3]
X[X > 3]
X[X != 3]
```

**10**.  В чем преимущество массивов NumPy по сравнению с обычными списками.  Чем обусловлено это преимущество?